// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using webapp1.Data;

#nullable disable

namespace webapp1.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250806142339_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("webapp1.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Electronics",
                            CreatedDate = new DateTime(2025, 7, 7, 10, 23, 38, 175, DateTimeKind.Local).AddTicks(9006),
                            IsActive = true,
                            Name = "Laptop",
                            Price = 999.99m
                        },
                        new
                        {
                            Id = 2,
                            Category = "Electronics",
                            CreatedDate = new DateTime(2025, 7, 12, 10, 23, 38, 178, DateTimeKind.Local).AddTicks(1580),
                            IsActive = true,
                            Name = "Mouse",
                            Price = 29.99m
                        },
                        new
                        {
                            Id = 3,
                            Category = "Electronics",
                            CreatedDate = new DateTime(2025, 7, 17, 10, 23, 38, 178, DateTimeKind.Local).AddTicks(1607),
                            IsActive = true,
                            Name = "Keyboard",
                            Price = 79.99m
                        },
                        new
                        {
                            Id = 4,
                            Category = "Electronics",
                            CreatedDate = new DateTime(2025, 7, 22, 10, 23, 38, 178, DateTimeKind.Local).AddTicks(1611),
                            IsActive = true,
                            Name = "Monitor",
                            Price = 299.99m
                        },
                        new
                        {
                            Id = 5,
                            Category = "Furniture",
                            CreatedDate = new DateTime(2025, 7, 27, 10, 23, 38, 178, DateTimeKind.Local).AddTicks(1614),
                            IsActive = true,
                            Name = "Desk Chair",
                            Price = 149.99m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
